# Generated by Django 3.2.5 on 2021-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('kakao', 'Kakao')], default='email', max_length=20),
        ),
    ]
