<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-08-12 13:30

=======
# Generated by Django 3.2.5 on 2021-08-13 09:14

import ckeditor_uploader.fields
>>>>>>> dd6180a299c83b829547291796778b5af5f5387f
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('users', '0005_alter_user_busker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_user_busker'),
>>>>>>> dd6180a299c83b829547291796778b5af5f5387f
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='broadcast_images/no_image.png', null=True, upload_to='studio_images')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='studio', serialize=False, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
<<<<<<< HEAD
                ('body', models.TextField(null=True)),
=======
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
>>>>>>> dd6180a299c83b829547291796778b5af5f5387f
                ('category', models.CharField(choices=[('NT', '공지사항'), ('BL', '자유게시판')], default='BL', max_length=40, null=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='studios.studio')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
