# Generated by Django 3.2.5 on 2021-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studio_images'),
        ),
    ]
