# Generated by Django 3.2.5 on 2021-08-10 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=40)),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='p_studio',
            new_name='studio_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='studio_host',
        ),
        migrations.AddField(
            model_name='post',
            name='category_field',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='host',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studio_images'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='timestampedmodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.timestampedmodel'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
