# Generated by Django 3.2.5 on 2021-08-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='timestampedmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='studio_host',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='timestampedmodel_ptr',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
