# Generated by Django 3.2.5 on 2021-08-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p_studio',
            new_name='studio_field',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='studio_host',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
