# Generated by Django 3.2.5 on 2021-08-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('studios', '0003_auto_20210809_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=40)),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='post',
            name='category_field',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
