# Generated by Django 3.2.5 on 2021-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_auto_20210811_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, default='broadcast_images/no_image.png', null=True, upload_to='studio_images'),
        ),
    ]
