# Generated by Django 3.2.5 on 2021-08-08 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0004_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Studio',
        ),
    ]
