# Generated by Django 3.2.5 on 2021-08-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_rename_post_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='title',
            new_name='name',
        ),
    ]
