# Generated by Django 3.2.5 on 2021-08-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_auto_20210809_1102 2'),
        ('studios', '0004_auto_20210809_1112 2'),
        ('studios', '0005_auto_20210809_1314'),
        ('studios', '0005_auto_20210809_1314 2'),
    ]

    operations = [
    ]
