# Generated by Django 3.2.5 on 2021-08-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_auto_20210810_0906'),
        ('studios', '0006_merge_20210810_0902'),
        ('studios', '0006_rename_title_studio_name'),
    ]

    operations = [
    ]
