# Generated by Django 3.2.5 on 2021-07-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='broadcasts',
            name='genre',
            field=models.ManyToManyField(blank=True, to='broadcasts.Genre'),
        ),
    ]
