# Generated by Django 3.2.5 on 2021-08-12 13:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_alter_broadcast_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
