# Generated by Django 3.2.5 on 2021-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_auto_20210813_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='on_air',
            field=models.BooleanField(null=True),
        ),
    ]
