# Generated by Django 3.2.5 on 2021-07-09 05:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_auto_20210709_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='country',
            field=django_countries.fields.CountryField(default='kr', max_length=2),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='picture_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcasts.picturequality'),
        ),
    ]
