# Generated by Django 3.2.5 on 2021-08-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_alter_broadcast_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='country',
        ),
    ]
