# Generated by Django 3.2.5 on 2021-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_alter_broadcast_on_air'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='on_air',
            field=models.BooleanField(default=False),
        ),
    ]
