# Generated by Django 3.2.5 on 2021-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_alter_broadcast_on_air'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/no_image.png', null=True, upload_to='broadcast_images'),
        ),
    ]
