# Generated by Django 3.2.5 on 2021-08-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_remove_broadcast_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
