# Generated by Django 3.2.5 on 2021-07-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_auto_20210709_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre'},
        ),
        migrations.AlterModelOptions(
            name='picturequality',
            options={'verbose_name': 'Picture Quality'},
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='broadcast_host',
            new_name='host',
        ),
    ]
