# Generated by Django 3.2.5 on 2021-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0005_auto_20210721_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcast_images'),
        ),
    ]
