# Generated by Django 3.2.5 on 2021-08-13 05:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0005_remove_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='country',
            field=django_countries.fields.CountryField(default='KR', max_length=2),
        ),
    ]
