# Generated by Django 3.2.5 on 2021-07-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0006_alter_broadcast_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='genre',
            new_name='genres',
        ),
    ]
