# Generated by Django 3.2.5 on 2021-08-09 11:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0008_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='country',
            field=django_countries.fields.CountryField(default='South Korea', max_length=2),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, default='broadcast_images/no_image.png', null=True, upload_to='broadcast_images'),
        ),
    ]
