# Generated by Django 3.2.5 on 2021-08-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcasts', '0009_auto_20210809_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='host',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='broadcasts', serialize=False, to='users.user'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='timestampedmodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.timestampedmodel'),
        ),
    ]
