# Generated by Django 3.2.5 on 2021-08-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0009_auto_20210809_1102 2'),
        ('broadcasts', '0010_auto_20210809_1314'),
        ('broadcasts', '0010_auto_20210809_1314 2'),
    ]

    operations = [
    ]
