# Generated by Django 3.2.5 on 2021-08-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0011_merge_20210810_0837'),
        ('broadcasts', '0011_merge_20210810_0903'),
    ]

    operations = [
    ]
